#################################################################################
# Copyright (c) 1999 - 2011 my-Channels Ltd
# Copyright (c) 2012 - 2019 Software AG, Darmstadt, Germany and/or its licensors
#
# SPDX-License-Identifier: Apache-2.0
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
#################################################################################
version: "3.3"
services:
  um:
# Create the node using image. 
    image:   sag-um:105.1
    restart: "no"
    container_name: sag-umserver
    ports:                         # expose the um server port, mappedport:exposed port
     - "9010:9000"
    volumes:                       # Persisting the data directory
     - data:/opt/softwareag/UniversalMessaging/server/umserver/data
     - logs:/opt/softwareag/UniversalMessaging/server/umserver/logs
     - licence:/opt/softwareag/UniversalMessaging/server/umserver/licence
     - conf:/opt/softwareag/common/conf
    environment:                  # runtime parameters
     - REALM_NAME=umserver
     - INIT_JAVA_MEM_SIZE=2048
     - MAX_JAVA_MEM_SIZE=2048
     - MAX_DIRECT_MEM_SIZE=1G
     - BASIC_AUTH_ENABLE=N
     - BASIC_AUTH_MANDATORY=N
    command: /opt/softwareag/UniversalMessaging/tools/runner/runUMTool.sh CreateChannel -rname=nsp://localhost:9000 -channelname=/wm/is/wm/prt/status/ChangeCommand
volumes:
  data:
  logs:
  licence:
  conf: